/* Oppdagerøya – den norske språkpakken
 *
 * Laget av lag-lydpakke.py. Skrives over hver gang.
 * Stemme: Piper no_NO-talesyntese-medium (VITS), trent på
 * Språkbankens talesyntesekorpus fra Nasjonalbiblioteket (CC0).
 *
 * Nøkkelen er setningen slik spillet sier den, i små bokstaver.
 */

var LYDFILER = {
 "a for ambulanse.": "ord-a-for-ambulanse.mp3",
 "a for anker.": "ord-a-for-anker.mp3",
 "a.": "bokstavnavn-a.mp3",
 "ambulanse.": "ordet-ambulanse.mp3",
 "anker.": "ordet-anker.mp3",
 "baller.": "telling-baller.mp3",
 "ballonger.": "telling-ballonger.mp3",
 "bananer.": "telling-bananer.mp3",
 "be for bil.": "ord-be-for-bil.mp3",
 "be for båt.": "ord-be-for-baat.mp3",
 "be.": "bokstavnavn-be.mp3",
 "bil.": "ordet-bil.mp3",
 "biler.": "telling-biler.mp3",
 "blomster.": "telling-blomster.mp3",
 "bra jobbet!": "ros-bra-jobbet.mp3",
 "bra jobbet, brumle!": "ros-bra-jobbet-brumle.mp3",
 "bra jobbet, bulder!": "ros-bra-jobbet-bulder.mp3",
 "bra jobbet, kaptein bart!": "ros-bra-jobbet-kaptein-bart.mp3",
 "bra jobbet, kaptein kalle!": "ros-bra-jobbet-kaptein-kalle.mp3",
 "bra jobbet, kaptein krok!": "ros-bra-jobbet-kaptein-krok.mp3",
 "bra jobbet, kaptein rødskjegg!": "ros-bra-jobbet-kaptein-roedskjegg.mp3",
 "bra jobbet, lynet!": "ros-bra-jobbet-lynet.mp3",
 "bra jobbet, piggen!": "ros-bra-jobbet-piggen.mp3",
 "bra jobbet, rappen!": "ros-bra-jobbet-rappen.mp3",
 "bra jobbet, rex!": "ros-bra-jobbet-rex.mp3",
 "bra jobbet, tass!": "ros-bra-jobbet-tass.mp3",
 "bra jobbet, turbo!": "ros-bra-jobbet-turbo.mp3",
 "bra kjørt!": "ros-bra-kjoert.mp3",
 "bra kjørt, bulder!": "ros-bra-kjoert-bulder.mp3",
 "bra kjørt, lynet!": "ros-bra-kjoert-lynet.mp3",
 "bra kjørt, rappen!": "ros-bra-kjoert-rappen.mp3",
 "bra kjørt, turbo!": "ros-bra-kjoert-turbo.mp3",
 "bra trampet!": "ros-bra-trampet.mp3",
 "bra trampet, brumle!": "ros-bra-trampet-brumle.mp3",
 "bra trampet, piggen!": "ros-bra-trampet-piggen.mp3",
 "bra trampet, rex!": "ros-bra-trampet-rex.mp3",
 "bra trampet, tass!": "ros-bra-trampet-tass.mp3",
 "båt.": "ordet-baat.mp3",
 "bøtter.": "telling-boetter.mp3",
 "campingbil.": "ordet-campingbil.mp3",
 "cowboy.": "ordet-cowboy.mp3",
 "de for delfin.": "ord-de-for-delfin.mp3",
 "de for dinosaur.": "ord-de-for-dinosaur.mp3",
 "de.": "bokstavnavn-de.mp3",
 "delfin.": "ordet-delfin.mp3",
 "den kan du nå!": "setning-den-kan-du-naa.mp3",
 "der ja! det er…": "setning-der-ja-det-er.mp3",
 "der var alle tallene! fra én til ti.": "setning-der-var-alle-tallene-fra-en-til-ti.mp3",
 "der var hele alfabetet! fra a til å.": "setning-der-var-hele-alfabetet-fra-a-til-aa.mp3",
 "det er navnet ditt!": "setning-det-er-navnet-ditt.mp3",
 "det klarte du!": "ros-det-klarte-du.mp3",
 "det klarte du, brumle!": "ros-det-klarte-du-brumle.mp3",
 "det klarte du, bulder!": "ros-det-klarte-du-bulder.mp3",
 "det klarte du, kaptein bart!": "ros-det-klarte-du-kaptein-bart.mp3",
 "det klarte du, kaptein kalle!": "ros-det-klarte-du-kaptein-kalle.mp3",
 "det klarte du, kaptein krok!": "ros-det-klarte-du-kaptein-krok.mp3",
 "det klarte du, kaptein rødskjegg!": "ros-det-klarte-du-kaptein-roedskjegg.mp3",
 "det klarte du, lynet!": "ros-det-klarte-du-lynet.mp3",
 "det klarte du, piggen!": "ros-det-klarte-du-piggen.mp3",
 "det klarte du, rappen!": "ros-det-klarte-du-rappen.mp3",
 "det klarte du, rex!": "ros-det-klarte-du-rex.mp3",
 "det klarte du, tass!": "ros-det-klarte-du-tass.mp3",
 "det klarte du, turbo!": "ros-det-klarte-du-turbo.mp3",
 "det var…": "setning-det-var.mp3",
 "dinosaur.": "ordet-dinosaur.mp3",
 "dobbelt-ve for wc.": "ord-dobbelt-ve-for-wc.mp3",
 "dobbelt-ve.": "bokstavnavn-dobbelt-ve.mp3",
 "e for elefant.": "ord-e-for-elefant.mp3",
 "e for eple.": "ord-e-for-eple.mp3",
 "e.": "bokstavnavn-e.mp3",
 "eff for flagg.": "ord-eff-for-flagg.mp3",
 "eff for fly.": "ord-eff-for-fly.mp3",
 "eff.": "bokstavnavn-eff.mp3",
 "egg.": "telling-egg.mp3",
 "eks for xylofon.": "ord-eks-for-xylofon.mp3",
 "eks.": "bokstavnavn-eks.mp3",
 "elefant.": "ordet-elefant.mp3",
 "ell for lastebil.": "ord-ell-for-lastebil.mp3",
 "ell for løve.": "ord-ell-for-loeve.mp3",
 "ell.": "bokstavnavn-ell.mp3",
 "emm for motorsykkel.": "ord-emm-for-motorsykkel.mp3",
 "emm for måne.": "ord-emm-for-maane.mp3",
 "emm.": "bokstavnavn-emm.mp3",
 "enn for nese.": "ord-enn-for-nese.mp3",
 "enn for nøkkel.": "ord-enn-for-noekkel.mp3",
 "enn.": "bokstavnavn-enn.mp3",
 "eple.": "ordet-eple.mp3",
 "epler.": "telling-epler.mp3",
 "err for rakett.": "ord-err-for-rakett.mp3",
 "err for rev.": "ord-err-for-rev.mp3",
 "err.": "bokstavnavn-err.mp3",
 "ess for skip.": "ord-ess-for-skip.mp3",
 "ess for sykkel.": "ord-ess-for-sykkel.mp3",
 "ess.": "bokstavnavn-ess.mp3",
 "fem epler.": "ord-fem-epler.mp3",
 "fem.": "tallnavn-fem.mp3",
 "fire biler.": "ord-fire-biler.mp3",
 "fire.": "tallnavn-fire.mp3",
 "fisker.": "telling-fisker.mp3",
 "flagg.": "ordet-flagg.mp3",
 "fly.": "ordet-fly.mp3",
 "full fart!": "ros-full-fart.mp3",
 "full fart, bulder!": "ros-full-fart-bulder.mp3",
 "full fart, lynet!": "ros-full-fart-lynet.mp3",
 "full fart, rappen!": "ros-full-fart-rappen.mp3",
 "full fart, turbo!": "ros-full-fart-turbo.mp3",
 "ge for gris.": "ord-ge-for-gris.mp3",
 "ge for gull.": "ord-ge-for-gull.mp3",
 "ge.": "bokstavnavn-ge.mp3",
 "godt seilt!": "ros-godt-seilt.mp3",
 "godt seilt, kaptein bart!": "ros-godt-seilt-kaptein-bart.mp3",
 "godt seilt, kaptein kalle!": "ros-godt-seilt-kaptein-kalle.mp3",
 "godt seilt, kaptein krok!": "ros-godt-seilt-kaptein-krok.mp3",
 "godt seilt, kaptein rødskjegg!": "ros-godt-seilt-kaptein-roedskjegg.mp3",
 "gris.": "ordet-gris.mp3",
 "gull.": "ordet-gull.mp3",
 "hai.": "ordet-hai.mp3",
 "hei!": "ros-hei.mp3",
 "hei, brumle!": "ros-hei-brumle.mp3",
 "hei, bulder!": "ros-hei-bulder.mp3",
 "hei, kaptein bart!": "ros-hei-kaptein-bart.mp3",
 "hei, kaptein kalle!": "ros-hei-kaptein-kalle.mp3",
 "hei, kaptein krok!": "ros-hei-kaptein-krok.mp3",
 "hei, kaptein rødskjegg!": "ros-hei-kaptein-roedskjegg.mp3",
 "hei, lynet!": "ros-hei-lynet.mp3",
 "hei, piggen!": "ros-hei-piggen.mp3",
 "hei, rappen!": "ros-hei-rappen.mp3",
 "hei, rex!": "ros-hei-rex.mp3",
 "hei, tass!": "ros-hei-tass.mp3",
 "hei, turbo!": "ros-hei-turbo.mp3",
 "her er…": "setning-her-er.mp3",
 "hus.": "ordet-hus.mp3",
 "hva skal dinosauren hete?": "setning-hva-skal-dinosauren-hete.mp3",
 "hva skal kapteinen hete?": "setning-hva-skal-kapteinen-hete.mp3",
 "hva skal racerbilen hete?": "setning-hva-skal-racerbilen-hete.mp3",
 "hva vil du gjøre?": "setning-hva-vil-du-gjoere.mp3",
 "hvilken bokstav begynner ambulanse på?": "forstelyd-hvilken-bokstav-begynner-ambulanse-paa.mp3",
 "hvilken bokstav begynner anker på?": "forstelyd-hvilken-bokstav-begynner-anker-paa.mp3",
 "hvilken bokstav begynner bil på?": "forstelyd-hvilken-bokstav-begynner-bil-paa.mp3",
 "hvilken bokstav begynner båt på?": "forstelyd-hvilken-bokstav-begynner-baat-paa.mp3",
 "hvilken bokstav begynner campingbil på?": "forstelyd-hvilken-bokstav-begynner-campingbil-paa.mp3",
 "hvilken bokstav begynner cowboy på?": "forstelyd-hvilken-bokstav-begynner-cowboy-paa.mp3",
 "hvilken bokstav begynner delfin på?": "forstelyd-hvilken-bokstav-begynner-delfin-paa.mp3",
 "hvilken bokstav begynner dinosaur på?": "forstelyd-hvilken-bokstav-begynner-dinosaur-paa.mp3",
 "hvilken bokstav begynner elefant på?": "forstelyd-hvilken-bokstav-begynner-elefant-paa.mp3",
 "hvilken bokstav begynner eple på?": "forstelyd-hvilken-bokstav-begynner-eple-paa.mp3",
 "hvilken bokstav begynner flagg på?": "forstelyd-hvilken-bokstav-begynner-flagg-paa.mp3",
 "hvilken bokstav begynner fly på?": "forstelyd-hvilken-bokstav-begynner-fly-paa.mp3",
 "hvilken bokstav begynner gris på?": "forstelyd-hvilken-bokstav-begynner-gris-paa.mp3",
 "hvilken bokstav begynner gull på?": "forstelyd-hvilken-bokstav-begynner-gull-paa.mp3",
 "hvilken bokstav begynner hai på?": "forstelyd-hvilken-bokstav-begynner-hai-paa.mp3",
 "hvilken bokstav begynner hus på?": "forstelyd-hvilken-bokstav-begynner-hus-paa.mp3",
 "hvilken bokstav begynner is på?": "forstelyd-hvilken-bokstav-begynner-is-paa.mp3",
 "hvilken bokstav begynner isbjørn på?": "forstelyd-hvilken-bokstav-begynner-isbjoern-paa.mp3",
 "hvilken bokstav begynner jordbær på?": "forstelyd-hvilken-bokstav-begynner-jordbaer-paa.mp3",
 "hvilken bokstav begynner juice på?": "forstelyd-hvilken-bokstav-begynner-juice-paa.mp3",
 "hvilken bokstav begynner kart på?": "forstelyd-hvilken-bokstav-begynner-kart-paa.mp3",
 "hvilken bokstav begynner kran på?": "forstelyd-hvilken-bokstav-begynner-kran-paa.mp3",
 "hvilken bokstav begynner lastebil på?": "forstelyd-hvilken-bokstav-begynner-lastebil-paa.mp3",
 "hvilken bokstav begynner løve på?": "forstelyd-hvilken-bokstav-begynner-loeve-paa.mp3",
 "hvilken bokstav begynner motorsykkel på?": "forstelyd-hvilken-bokstav-begynner-motorsykkel-paa.mp3",
 "hvilken bokstav begynner måne på?": "forstelyd-hvilken-bokstav-begynner-maane-paa.mp3",
 "hvilken bokstav begynner nese på?": "forstelyd-hvilken-bokstav-begynner-nese-paa.mp3",
 "hvilken bokstav begynner nøkkel på?": "forstelyd-hvilken-bokstav-begynner-noekkel-paa.mp3",
 "hvilken bokstav begynner ost på?": "forstelyd-hvilken-bokstav-begynner-ost-paa.mp3",
 "hvilken bokstav begynner oter på?": "forstelyd-hvilken-bokstav-begynner-oter-paa.mp3",
 "hvilken bokstav begynner papegøye på?": "forstelyd-hvilken-bokstav-begynner-papegoeye-paa.mp3",
 "hvilken bokstav begynner politibil på?": "forstelyd-hvilken-bokstav-begynner-politibil-paa.mp3",
 "hvilken bokstav begynner quiz på?": "forstelyd-hvilken-bokstav-begynner-quiz-paa.mp3",
 "hvilken bokstav begynner rakett på?": "forstelyd-hvilken-bokstav-begynner-rakett-paa.mp3",
 "hvilken bokstav begynner rev på?": "forstelyd-hvilken-bokstav-begynner-rev-paa.mp3",
 "hvilken bokstav begynner skip på?": "forstelyd-hvilken-bokstav-begynner-skip-paa.mp3",
 "hvilken bokstav begynner sykkel på?": "forstelyd-hvilken-bokstav-begynner-sykkel-paa.mp3",
 "hvilken bokstav begynner tiger på?": "forstelyd-hvilken-bokstav-begynner-tiger-paa.mp3",
 "hvilken bokstav begynner traktor på?": "forstelyd-hvilken-bokstav-begynner-traktor-paa.mp3",
 "hvilken bokstav begynner ugle på?": "forstelyd-hvilken-bokstav-begynner-ugle-paa.mp3",
 "hvilken bokstav begynner ulv på?": "forstelyd-hvilken-bokstav-begynner-ulv-paa.mp3",
 "hvilken bokstav begynner vaffel på?": "forstelyd-hvilken-bokstav-begynner-vaffel-paa.mp3",
 "hvilken bokstav begynner vulkan på?": "forstelyd-hvilken-bokstav-begynner-vulkan-paa.mp3",
 "hvilken bokstav begynner wc på?": "forstelyd-hvilken-bokstav-begynner-wc-paa.mp3",
 "hvilken bokstav begynner xylofon på?": "forstelyd-hvilken-bokstav-begynner-xylofon-paa.mp3",
 "hvilken bokstav begynner yoghurt på?": "forstelyd-hvilken-bokstav-begynner-yoghurt-paa.mp3",
 "hvilken bokstav begynner zebra på?": "forstelyd-hvilken-bokstav-begynner-zebra-paa.mp3",
 "hvilken bokstav begynner åtte på?": "forstelyd-hvilken-bokstav-begynner-aatte-paa.mp3",
 "hvilken bokstav begynner æsj på?": "forstelyd-hvilken-bokstav-begynner-aesj-paa.mp3",
 "hvilken bokstav begynner øy på?": "forstelyd-hvilken-bokstav-begynner-oey-paa.mp3",
 "hvilken bokstav begynner øye på?": "forstelyd-hvilken-bokstav-begynner-oeye-paa.mp3",
 "hvor mange baller?": "telling-hvor-mange-baller.mp3",
 "hvor mange ballonger?": "telling-hvor-mange-ballonger.mp3",
 "hvor mange bananer?": "telling-hvor-mange-bananer.mp3",
 "hvor mange biler?": "telling-hvor-mange-biler.mp3",
 "hvor mange blomster?": "telling-hvor-mange-blomster.mp3",
 "hvor mange bøtter?": "telling-hvor-mange-boetter.mp3",
 "hvor mange egg?": "telling-hvor-mange-egg.mp3",
 "hvor mange epler?": "telling-hvor-mange-epler.mp3",
 "hvor mange fisker?": "telling-hvor-mange-fisker.mp3",
 "hvor mange jordbær?": "telling-hvor-mange-jordbaer.mp3",
 "hvor mange sko?": "telling-hvor-mange-sko.mp3",
 "hvor mange stjerner?": "telling-hvor-mange-stjerner.mp3",
 "hå for hai.": "ord-haa-for-hai.mp3",
 "hå for hus.": "ord-haa-for-hus.mp3",
 "hå.": "bokstavnavn-haa.mp3",
 "i for is.": "ord-i-for-is.mp3",
 "i for isbjørn.": "ord-i-for-isbjoern.mp3",
 "i.": "bokstavnavn-i.mp3",
 "is.": "ordet-is.mp3",
 "isbjørn.": "ordet-isbjoern.mp3",
 "je for jordbær.": "ord-je-for-jordbaer.mp3",
 "je for juice.": "ord-je-for-juice.mp3",
 "je.": "bokstavnavn-je.mp3",
 "jordbær.": "ordet-jordbaer.mp3",
 "juice.": "ordet-juice.mp3",
 "kart.": "ordet-kart.mp3",
 "kjempebra!": "ros-kjempebra.mp3",
 "kjempebra, brumle!": "ros-kjempebra-brumle.mp3",
 "kjempebra, piggen!": "ros-kjempebra-piggen.mp3",
 "kjempebra, rex!": "ros-kjempebra-rex.mp3",
 "kjempebra, tass!": "ros-kjempebra-tass.mp3",
 "kjør til…": "setning-kjoer-til.mp3",
 "kran.": "ordet-kran.mp3",
 "ku for quiz.": "ord-ku-for-quiz.mp3",
 "ku.": "bokstavnavn-ku.mp3",
 "kå for kart.": "ord-kaa-for-kart.mp3",
 "kå for kran.": "ord-kaa-for-kran.mp3",
 "kå.": "bokstavnavn-kaa.mp3",
 "land i sikte!": "ros-land-i-sikte.mp3",
 "land i sikte, kaptein bart!": "ros-land-i-sikte-kaptein-bart.mp3",
 "land i sikte, kaptein kalle!": "ros-land-i-sikte-kaptein-kalle.mp3",
 "land i sikte, kaptein krok!": "ros-land-i-sikte-kaptein-krok.mp3",
 "land i sikte, kaptein rødskjegg!": "ros-land-i-sikte-kaptein-roedskjegg.mp3",
 "lastebil.": "ordet-lastebil.mp3",
 "løve.": "ordet-loeve.mp3",
 "motorsykkel.": "ordet-motorsykkel.mp3",
 "måne.": "ordet-maane.mp3",
 "navnet ditt begynner med…": "setning-navnet-ditt-begynner-med.mp3",
 "nese.": "ordet-nese.mp3",
 "ni bananer.": "ord-ni-bananer.mp3",
 "ni.": "tallnavn-ni.mp3",
 "nå prøver vi en vanskeligere en.": "setning-naa-proever-vi-en-vanskeligere-en.mp3",
 "nøkkel.": "ordet-noekkel.mp3",
 "o for ost.": "ord-o-for-ost.mp3",
 "o for oter.": "ord-o-for-oter.mp3",
 "o.": "bokstavnavn-o.mp3",
 "ost.": "ordet-ost.mp3",
 "oter.": "ordet-oter.mp3",
 "papegøye.": "ordet-papegoeye.mp3",
 "pe for papegøye.": "ord-pe-for-papegoeye.mp3",
 "pe for politibil.": "ord-pe-for-politibil.mp3",
 "pe.": "bokstavnavn-pe.mp3",
 "politibil.": "ordet-politibil.mp3",
 "prøv en gang til.": "setning-proev-en-gang-til.mp3",
 "quiz.": "ordet-quiz.mp3",
 "rakett.": "ordet-rakett.mp3",
 "rev.": "ordet-rev.mp3",
 "se for campingbil.": "ord-se-for-campingbil.mp3",
 "se for cowboy.": "ord-se-for-cowboy.mp3",
 "se her!": "setning-se-her.mp3",
 "se.": "bokstavnavn-se.mp3",
 "seil til…": "setning-seil-til.mp3",
 "seks fisker.": "ord-seks-fisker.mp3",
 "seks.": "tallnavn-seks.mp3",
 "sett for zebra.": "ord-sett-for-zebra.mp3",
 "sett.": "bokstavnavn-sett.mp3",
 "sju blomster.": "ord-sju-blomster.mp3",
 "sju.": "tallnavn-sju.mp3",
 "skip.": "ordet-skip.mp3",
 "sko.": "telling-sko.mp3",
 "stjerner.": "telling-stjerner.mp3",
 "sykkel.": "ordet-sykkel.mp3",
 "så flink du er!": "ros-saa-flink-du-er.mp3",
 "så flink du er, brumle!": "ros-saa-flink-du-er-brumle.mp3",
 "så flink du er, bulder!": "ros-saa-flink-du-er-bulder.mp3",
 "så flink du er, kaptein bart!": "ros-saa-flink-du-er-kaptein-bart.mp3",
 "så flink du er, kaptein kalle!": "ros-saa-flink-du-er-kaptein-kalle.mp3",
 "så flink du er, kaptein krok!": "ros-saa-flink-du-er-kaptein-krok.mp3",
 "så flink du er, kaptein rødskjegg!": "ros-saa-flink-du-er-kaptein-roedskjegg.mp3",
 "så flink du er, lynet!": "ros-saa-flink-du-er-lynet.mp3",
 "så flink du er, piggen!": "ros-saa-flink-du-er-piggen.mp3",
 "så flink du er, rappen!": "ros-saa-flink-du-er-rappen.mp3",
 "så flink du er, rex!": "ros-saa-flink-du-er-rex.mp3",
 "så flink du er, tass!": "ros-saa-flink-du-er-tass.mp3",
 "så flink du er, turbo!": "ros-saa-flink-du-er-turbo.mp3",
 "så kommer…": "setning-saa-kommer.mp3",
 "te for tiger.": "ord-te-for-tiger.mp3",
 "te for traktor.": "ord-te-for-traktor.mp3",
 "te.": "bokstavnavn-te.mp3",
 "ti jordbær.": "ord-ti-jordbaer.mp3",
 "ti.": "tallnavn-ti.mp3",
 "tiger.": "ordet-tiger.mp3",
 "to egg.": "ord-to-egg.mp3",
 "to.": "tallnavn-to.mp3",
 "traktor.": "ordet-traktor.mp3",
 "tramp til…": "setning-tramp-til.mp3",
 "tre baller.": "ord-tre-baller.mp3",
 "tre.": "tallnavn-tre.mp3",
 "trykk på den.": "setning-trykk-paa-den.mp3",
 "trykk på hver enkelt og tell.": "setning-trykk-paa-hver-enkelt-og-tell.mp3",
 "u for ugle.": "ord-u-for-ugle.mp3",
 "u for ulv.": "ord-u-for-ulv.mp3",
 "u.": "bokstavnavn-u.mp3",
 "ugle.": "ordet-ugle.mp3",
 "ulv.": "ordet-ulv.mp3",
 "vaffel.": "ordet-vaffel.mp3",
 "ve for vaffel.": "ord-ve-for-vaffel.mp3",
 "ve for vulkan.": "ord-ve-for-vulkan.mp3",
 "ve.": "bokstavnavn-ve.mp3",
 "vulkan.": "ordet-vulkan.mp3",
 "wc.": "ordet-wc.mp3",
 "xylofon.": "ordet-xylofon.mp3",
 "y for yoghurt.": "ord-y-for-yoghurt.mp3",
 "y.": "bokstavnavn-y.mp3",
 "yoghurt.": "ordet-yoghurt.mp3",
 "zebra.": "ordet-zebra.mp3",
 "å for åtte.": "ord-aa-for-aatte.mp3",
 "å.": "bokstavnavn-aa.mp3",
 "åtte stjerner.": "ord-aatte-stjerner.mp3",
 "åtte.": "tallnavn-aatte.mp3",
 "æ for æsj.": "ord-ae-for-aesj.mp3",
 "æ.": "bokstavnavn-ae.mp3",
 "æsj.": "ordet-aesj.mp3",
 "én dinosaur.": "ord-en-dinosaur.mp3",
 "én.": "tallnavn-en.mp3",
 "ø for øy.": "ord-oe-for-oey.mp3",
 "ø for øye.": "ord-oe-for-oeye.mp3",
 "ø.": "bokstavnavn-oe.mp3",
 "øy.": "ordet-oey.mp3",
 "øye.": "ordet-oeye.mp3"
};
